# Generated by Django 5.1 on 2024-08-12 06:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend_app', '0004_user_delete_customuser'),
    ]

    operations = [
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('age', models.IntegerField()),
                ('gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female'), ('Other', 'Other')], max_length=10)),
                ('phone_no', models.CharField(max_length=15)),
                ('address', models.CharField(max_length=255)),
                ('shift', models.CharField(choices=[('Day', 'Day'), ('Afternoon', 'Afternoon'), ('Night', 'Night')], max_length=20)),
                ('dob', models.DateField()),
                ('email', models.EmailField(max_length=254, unique=True)),
            ],
        ),
    ]
