# Generated by Django 5.1 on 2024-08-13 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend_app', '0006_timeoffrequest'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShiftSwapRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('yourEmailID', models.EmailField(max_length=254)),
                ('yourName', models.CharField(max_length=100)),
                ('swapWithEmailID', models.EmailField(max_length=254)),
                ('swapWithName', models.CharField(max_length=100)),
                ('reason', models.TextField()),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Approved', 'Approved'), ('Denied', 'Denied')], max_length=10)),
            ],
        ),
    ]
