# Generated by Django 5.1 on 2024-08-13 13:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend_app', '0007_shiftswaprequest'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Staff',
        ),
    ]
