# Generated by Django 5.1 on 2024-08-13 13:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend_app', '0010_shift'),
    ]

    operations = [
        migrations.RenameField(
            model_name='shift',
            old_name='staff_details',
            new_name='staff_data',
        ),
    ]
