# Generated by Django 5.1 on 2024-08-13 13:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend_app', '0012_attendance'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shift',
            name='staff_data',
        ),
    ]
